package ru.fireshine.laba2.utils;

import java.util.ArrayList;
import java.util.List;

public class Utils {
	
	public static String createDishesTable() {
		String table = "CREATE CACHED TABLE IF NOT EXISTS Dishes ("
			+ "id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,"
			+ "name VARCHAR(255) NOT NULL,"
			+ "cookery VARCHAR(255) NOT NULL,"
			+ "calorie REAL NOT NULL,"
			+ "ingredients VARCHAR(1024) NOT NULL,"
			+ "cost REAL NOT NULL"
			+ ")";
		return table;
	}
	
	public static String createRestaurantsTable() {
		String table = "CREATE CACHED TABLE IF NOT EXISTS Restaurants ("
			+ "id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,"
			+ "name VARCHAR(255) NOT NULL,"
			+ "cookery VARCHAR(255) NOT NULL,"
			+ "address VARCHAR(255) NOT NULL"
			+ ")";
		return table;
	}
	
	public static String createRestaurantsDishes() {
		String table = "CREATE CACHED TABLE IF NOT EXISTS RestaurantsDishes ("
			+ "restaurantId BIGINT NOT NULL,"
			+ "dishId BIGINT NOT NULL,"
			+ "PRIMARY KEY(RESTAURANTID, DISHID)"
			+ ")";
		return table;
	}
	
	public static List<String> fillDishesTable() {
		String insert = "INSERT INTO DISHES (name, cookery, calorie, ingredients, cost)";
		List<String> values = new ArrayList<>();
		values.add(insert
				+ "VALUES('суши', 'японская кухня', 87, 'some ingredients', 90);");
		values.add(insert
				+ "VALUES('роллы', 'японская кухня', 121, 'some ingredients', 320);");
		values.add(insert
				+ "VALUES('сашими', 'японская кухня', 37, 'some ingredients', 230);");
		values.add(insert
				+ "VALUES('мисо суп', 'японская кухня', 82, 'some ingredients', 200);");
		values.add(insert
				+ "VALUES('кофе', 'напиток', 30, 'some ingredients', 150);");
		values.add(insert
				+ "VALUES('чай', 'напиток', 43, 'some ingredients', 100);");
		values.add(insert
				+ "VALUES('пирожное', 'десерт', 400, 'some ingredients', 170);");
		values.add(insert
				+ "VALUES('круассан', 'десерт', 343, 'some ingredients', 135);");
		values.add(insert
				+ "VALUES('мороженое', 'десерт', 260, 'some ingredients', 120);");
		values.add(insert
				+ "VALUES('хинкали', 'грузинская кухня', 192, 'some ingredients', 340);");
		values.add(insert
				+ "VALUES('хачапури', 'грузинская кухня', 223, 'some ingredients', 140);");
		values.add(insert
				+ "VALUES('шашлык', 'мясное блюдо', 326, 'some ingredients', 500);");
		values.add(insert
				+ "VALUES('стейк', 'мясное блюдо', 271, 'some ingredients', 650);");
		values.add(insert
				+ "VALUES('колбаски', 'мясное блюдо', 283, 'some ingredients', 450);");
		values.add(insert
				+ "VALUES('пицца', 'итальянская кухня', 266, 'some ingredients', 300);");
		values.add(insert
				+ "VALUES('паста', 'итальянская кухня', 273, 'some ingredients', 270);");
		values.add(insert
				+ "VALUES('вафли', 'десерт', 367, 'some ingredients', 160);");
		return values;
	}
	
	public static List<String> fillRestaurantsTable() {
		String insert = "INSERT INTO RESTAURANTS (name, cookery, address)";
		List<String> values = new ArrayList<>();
		values.add(insert
				+ "VALUES('Тануки', 'Японская кухня', 'Цветочный Бульвар, 5');");
		values.add(insert
				+ "VALUES('Перчини', 'Итальянская кухня', 'пр. Победы, 9');");
		values.add(insert
				+ "VALUES('Старбакс', 'Кофейня', 'ул. Гагарина, 12');");
		values.add(insert
				+ "VALUES('Carrie', 'Кофейня', 'ул. Строителей, 31');");
		values.add(insert
				+ "VALUES('Хинкали&Хачапури', 'Грузинская кухня', 'ул. Льва Толстого, 118');");
		values.add(insert
				+ "VALUES('Ваще огонь', 'мясной', 'ул. Крутая, 404');");
		values.add(insert
				+ "VALUES('Хокку', 'Японская кухня', 'ул. Сакуры, 2');");
		return values;
	}
	
	public static List<String> fillRestrauntsDishesTable() {
		List<String> values = new ArrayList<>();
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(1,1);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(1,2);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(1,3);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(1,4);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(2,15);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(2,16);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(3,5);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(3,6);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(3,7);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(3,8);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(4,5);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(4,6);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(4,7);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(4,9);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(4,17);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(5,10);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(5,11);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(5,12);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(6,12);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(6,13);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(6,14);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(7,1);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(7,2);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(7,3);");
		values.add("INSERT INTO RESTAURANTSDISHES VALUES(7,4);");
		return values;
	}
	
}
